import React from 'react'
import { Text, TouchableOpacity, View } from 'react-native'
import tailwind from 'tailwind-rn'
import { ScreenProps } from '../../App'
import Appbar from '../../components/shared/appbar-header.component'
import Container from '../../components/shared/container.component'

const TransactionDetails: React.FunctionComponent<ScreenProps<'TransactionDetail'>> = ({ navigation }) => {
        return (
            <Container>
                <Appbar navigation={navigation} screenTitle="Transactions"/>
                <View style={tailwind("bg-white mx-3 p-2 bg-opacity-50 my-6 w-11/12")}>
                    <Text style={tailwind("p-2")}>Recent Transactions</Text>
                    <View style={tailwind("border border-gray-400")}></View>
                    <View style={tailwind("w-full")}>
                        <View style={tailwind("justify-between flex-row w-full p-2")}>
                            <Text style={tailwind("flex-1 text-blue-700")}>Purpose of Transaction: </Text>
                            <Text style={tailwind("flex-1 ")}>Savings</Text>
                        </View>
                        <View style={tailwind("justify-between flex-row w-full p-2")}>
                            <Text style={tailwind("flex-1 text-blue-700")}>Amount: </Text>
                            <Text style={tailwind("flex-1 ")}>XAF 200000</Text>
                        </View>
                        <View style={tailwind("justify-between flex-row w-full p-2")}>
                            <Text style={tailwind("flex-1 text-blue-700")}>Date: </Text>
                            <Text style={tailwind("flex-1")}>August 27 2021</Text>
                        </View>
                        <View style={tailwind("justify-between flex-row w-full p-2")}>
                            <Text style={tailwind("flex-1 text-blue-700")}>Purpose of Transaction: </Text>
                            <Text style={tailwind("flex-1")}>Savings</Text>
                        </View>
                    </View>
                    <View style={tailwind("p-2")}>  
                        <Text style={tailwind("text-blue-700 py-2")}>Notes</Text>
                        <Text>This section will hold the ending notes that are generated by client</Text>
                    </View>
                    <TouchableOpacity
                        onPress={()=> {}}
                        style={tailwind(
                            "bg-blue-700 items-center justify-center self-start p-3 px-6 m-3"
                        )}
                    >
                        <Text style={tailwind("text-white")}>Back</Text>
                    </TouchableOpacity>
                    

                </View>
                
            </Container>
        )
    
}

export default TransactionDetails
